import { describe, expect, it } from "vitest";
import type { Approval } from "@/types/approval";
import type { Evidence, WorkItem } from "@/types/workItem";
import { executeWorkItemCommandUseCase } from "@/lib/application/executeWorkItemCommand";
import { createSessionStorageWorkItemRepository, SESSION_WORK_ITEM_REPOSITORY_KEY } from "./sessionStorageWorkItemRepository";

class FakeStorage { private values = new Map<string, string>(); getItem(key: string) { return this.values.get(key) ?? null; } setItem(key: string, value: string) { this.values.set(key, value); } }
const item = (id = "w"): WorkItem => ({ id, kind: "matching-proposal", source: { type: "manual", ref: "x" }, sourceVersion: "1", createdAt: "2026-09-19", updatedAt: "2026-09-19", assignedAgentId: null, assignedHumanId: "h", relations: { opportunityIds: [], personIds: [], partnerIds: [], clientIds: [], companyIds: [], parentWorkItemId: null, supersededByWorkItemId: null }, status: "needs_human_input", nextAction: { kind: "provide_human_input", ownerType: "human" }, dueAt: null, missingInfo: [], conflicts: [], evidenceIds: [], proposalDecisions: [], currentDeliverableId: null, approvalRequired: true, currentApprovalId: null, execution: { attempt: 1, lastAgentId: null, lastError: null, resumeStatus: null }, mode: "real", schemaVersion: 1 });
const approval = (id = "a"): Approval => ({ id, workItemId: "w", targetDeliverableId: "d", targetDeliverableVersion: 1, targetDeliverableHash: "h", targetDecisionSnapshotHash: "s", requestedBy: { type: "agent", id: "a" }, requestedAt: "2026-09-19", approver: null, decidedBy: null, decidedAt: null, scope: { fields: [], permits: ["prepare-only"], conditions: [] }, expiresAt: "2026-09-20", state: "pending", decisionComment: null, rejectionReason: null, supersedesApprovalId: null, invalidation: null });
const evidence = (id = "e"): Evidence => ({ id, workItemId: "w", kind: "human_confirmation", claim: "x", sourceRef: "human:h", sourceVersion: "1", excerpt: "x", producedBy: { type: "human", id: "h" }, producedAt: "2026-09-19", observedAt: null, verifiedAt: null, validUntil: null });
describe("session storage work item repository", () => {
  it("persists entities across repository instances and upserts deterministically", async () => { const storage = new FakeStorage(); const repo = createSessionStorageWorkItemRepository(storage); await repo.saveWorkItem(item("b")); await repo.saveWorkItem(item("a")); await repo.saveApproval(approval()); await repo.saveEvidence(evidence()); expect((await createSessionStorageWorkItemRepository(storage).listWorkItems()).map(x => x.id)).toEqual(["a", "b"]); expect(await createSessionStorageWorkItemRepository(storage).getApproval("a")).toMatchObject({ state: "pending" }); expect(await repo.getEvidence("missing")).toBeNull(); });
  it("preserves clone safety and schema version", async () => { const storage = new FakeStorage(); const repo = createSessionStorageWorkItemRepository(storage); const w = item(); await repo.saveWorkItem(w); w.status = "closed"; const got = await repo.getWorkItem("w"); if (got) got.status = "closed"; expect((await repo.getWorkItem("w"))?.status).toBe("needs_human_input"); expect(JSON.parse(storage.getItem(SESSION_WORK_ITEM_REPOSITORY_KEY)!).version).toBe(1); });
  it("handles corrupt JSON and invalid schema safely", async () => { const storage = new FakeStorage(); storage.setItem(SESSION_WORK_ITEM_REPOSITORY_KEY, "not-json"); await expect(createSessionStorageWorkItemRepository(storage).listWorkItems()).rejects.toThrow("repository-corrupt-data"); storage.setItem(SESSION_WORK_ITEM_REPOSITORY_KEY, JSON.stringify({ version: 2 })); await expect(createSessionStorageWorkItemRepository(storage).listWorkItems()).rejects.toThrow("repository-invalid-schema"); });
  it("works with the Application Use Case and a recreated repository", async () => { const storage = new FakeStorage(); const repo = createSessionStorageWorkItemRepository(storage); const work = { ...item(), status: "quality_check" as const }; await repo.saveWorkItem(work); const result = await executeWorkItemCommandUseCase({ repositories: repo, command: { type: "return-for-rework", commandId: "c", workItemId: "w", actorId: "h", issuedAt: "2026-09-19T12:00:00Z", reason: "修正" }, effectContext: { at: "2026-09-19T12:00:00Z", actor: { type: "human", id: "h" } } }); expect(result).toMatchObject({ ok: true, workItem: { status: "returned_for_rework" } }); expect((await createSessionStorageWorkItemRepository(storage).getWorkItem("w"))?.status).toBe("returned_for_rework"); });
});
