"use client";

import Link from "next/link";
import { Check, FastForward, Pause, Play, RotateCcw, Square, X } from "lucide-react";
import { demoCandidates, demoChecks, demoJob, demoRecommendation } from "@/data/demoScenario";
import type { DemoScenario, DemoScenarioId, DemoSpeed, DemoStatus, DemoStep } from "@/types/demo";
import s from "./VisualOffice.module.css";

export function DemoStart({ scenarios, scenario, onScenario, onStart, speed, onSpeed }: { scenarios: DemoScenario[]; scenario: DemoScenario; onScenario: (id: DemoScenarioId) => void; onStart: () => void; speed: DemoSpeed; onSpeed: (speed: DemoSpeed) => void }) {
  return <section className={s.demoLauncher} aria-label="デモシナリオ選択">
    <div className={s.demoScenarioTabs} role="tablist" aria-label="デモを選択">{scenarios.map(item => <button key={item.id} role="tab" aria-selected={scenario.id === item.id} className={scenario.id === item.id ? s.demoScenarioActive : ""} onClick={() => onScenario(item.id)}><strong>{item.title}</strong><span>{item.estimatedDuration}</span></button>)}</div>
    <div className={s.demoStart}><div><strong>{scenario.title}</strong><span>{scenario.description}</span></div><label>速度<select value={speed} onChange={event => onSpeed(event.target.value as DemoSpeed)}><option value="normal">通常</option><option value="fast">高速</option></select></label><button onClick={onStart}><Play size={15} />デモを開始</button></div>
  </section>;
}

export function DemoControls({ scenario, status, step, progress, stepProgress, onPause, onResume, onStop, onRestart }: { scenario: DemoScenario; status: DemoStatus; step: DemoStep; progress: number; stepProgress: number; onPause: () => void; onResume: () => void; onStop: () => void; onRestart: () => void }) {
  return <aside className={s.demoControls} aria-live="polite"><header><div><span>LIVE DEMO</span><strong>{scenario.title}</strong></div><b>{status === "paused" ? "一時停止中" : status === "completed" ? "完了" : "実行中"}</b></header><div className={s.demoStepLine}><strong>Step {step.id} / {scenario.steps.length}</strong><span>{step.title}</span><em>{progress}%</em></div><div className={s.demoProgress}><i style={{ width: `${progress}%` }} /></div><p><span>担当AI</span><b>{step.agentNames.join("・")}</b></p><p><span>現在の処理</span><b>{step.process}</b></p>{step.progressLabel && <div className={s.matchProgress}><FastForward size={13} />{step.progressLabel} {stepProgress}%</div>}{step.highlights && <div className={s.demoHighlights}>{step.highlights.map(item => <span key={item}>{item}</span>)}</div>}{step.handoffCard && <div className={s.demoHandoffCard}><Check size={12} />{step.handoffCard}</div>}<footer>{status === "paused" ? <button onClick={onResume}><Play size={14} />再開</button> : status === "running" ? <button onClick={onPause}><Pause size={14} />一時停止</button> : null}<button onClick={onStop}><Square size={13} />停止</button><button onClick={onRestart}><RotateCcw size={14} />最初から</button></footer></aside>;
}

export function DemoResult({ scenario, logs, onClose, onRestart, onSelectAnother }: { scenario: DemoScenario; logs: string[]; onClose: () => void; onRestart: () => void; onSelectAnother: () => void }) {
  return <div className={s.demoBackdrop} onMouseDown={event => event.target === event.currentTarget && onClose()}><section className={s.demoResult} role="dialog" aria-modal="true" aria-labelledby="demo-result-title"><button className={s.demoClose} onClick={onClose} aria-label="デモ結果を閉じる"><X size={19} /></button><div className={s.demoSuccess}><Check size={22} /><div><span>DEMO COMPLETE</span><h2 id="demo-result-title">{scenario.result.title}</h2></div></div><div className={s.demoJob}><strong>{scenario.title}</strong><span>{scenario.result.summary}</span><p>完了Step {scenario.steps.length} / {scenario.steps.length} ・ フロア移動 {scenario.floorMoves}回</p></div><h3>担当AI</h3><div className={s.demoChecks}>{scenario.participants.map(item => <span key={item}>{item}</span>)}</div><h3>成果</h3><div className={s.demoMetrics}>{scenario.result.metrics.map(metric => <article key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong></article>)}</div>{scenario.id === "proposal-prep" && <><div className={s.demoJob}><strong>{demoJob.name}</strong><span>{demoJob.skills}</span><p>{demoJob.workStyle} ・ {demoJob.rate} ・ {demoJob.start}開始 ・ {demoJob.openings}</p></div><h3>候補者3名</h3><div className={s.demoCandidates}>{demoCandidates.map((candidate, index) => <article key={candidate.name} className={index === 0 ? s.bestCandidate : ""}><header><strong>{index + 1}. {candidate.name}</strong><b>{candidate.score}%</b></header><p>Java {candidate.java} / Spring Boot {candidate.spring} / SQL {candidate.sql}</p><span>{candidate.verdict}</span><small>{candidate.caution}</small></article>)}</div><h3>最優先候補の推薦文</h3><blockquote>{demoRecommendation}</blockquote><div className={s.demoChecks}>{demoChecks.map(item => <span key={item}>{item}</span>)}</div></>}<h3>作成された成果物</h3><div className={s.demoChecks}>{scenario.result.artifacts.map(item => <span key={item}>{item}</span>)}</div><h3>Dashboard反映</h3><blockquote>{scenario.result.dashboardSummary}・優先タスク「{scenario.result.priorityTask}」</blockquote><details><summary>実行ログ概要（{logs.length}件）</summary><ol>{logs.map((log, index) => <li key={`${log}-${index}`}>{log}</li>)}</ol></details><footer><Link href="/dashboard">Dashboardを開く</Link><button onClick={onRestart}><RotateCcw size={14} />最初から再実行</button><button onClick={onSelectAnother}>別のデモを選ぶ</button></footer></section></div>;
}
