import { describe, expect, it } from "vitest";
import type { OfficeV3DemoResult } from "@/types/officeV3ClaudeDemo";
import { createInMemoryWorkItemRepository } from "@/lib/repositories/inMemoryWorkItemRepository";
import { initializeDemoWorkItemsFromResults } from "./initializeDemoWorkItems";

const result = (scenarioId: OfficeV3DemoResult["scenarioId"], completedAt = "2026-09-19T00:00:00Z"): OfficeV3DemoResult => ({ scenarioId, completedAt, resultTitle: scenarioId, resultSummary: "summary", finalAgentId: "agent" } as OfficeV3DemoResult);
const options = { now: "2026-09-19T12:00:00Z" };
describe("demo work item initializer", () => {
  it("creates four demo WorkItems on first run and skips them on rerun", async () => { const repo = createInMemoryWorkItemRepository(); const results = [result("matching-proposal"), result("new-client-outreach"), result("candidate-screening"), result("bp-alliance")]; expect(await initializeDemoWorkItemsFromResults(results, repo, options)).toMatchObject({ ok: true, created: 4, skippedExisting: 0 }); const rerun = await initializeDemoWorkItemsFromResults(results, repo, options); expect(rerun).toMatchObject({ ok: true, created: 0, skippedExisting: 4 }); expect((await repo.listWorkItems()).every(item => item.mode === "demo")).toBe(true); });
  it("protects existing human changes, adds new results, and never deletes missing results", async () => { const repo = createInMemoryWorkItemRepository(); const initial = [result("matching-proposal"), result("new-client-outreach"), result("candidate-screening"), result("bp-alliance")]; await initializeDemoWorkItemsFromResults(initial, repo, options); const existing = await repo.getWorkItem("wi-demo-matching-proposal"); await repo.saveWorkItem({ ...existing!, status: "closed" }); const next = await initializeDemoWorkItemsFromResults([result("matching-proposal", "later"), result("new-client-outreach"), result("candidate-screening")], repo, options); expect(next).toMatchObject({ created: 0, skippedExisting: 3 }); expect((await repo.getWorkItem("wi-demo-matching-proposal"))?.status).toBe("closed"); expect((await repo.listWorkItems())).toHaveLength(4); });
  it("deduplicates repeated deterministic IDs and does nothing for zero results", async () => { const repo = createInMemoryWorkItemRepository(); expect(await initializeDemoWorkItemsFromResults([], repo, options)).toMatchObject({ created: 0, skippedExisting: 0, skippedDuplicate: 0 }); expect(await initializeDemoWorkItemsFromResults([result("matching-proposal"), result("matching-proposal", "later")], repo, options)).toMatchObject({ created: 1, skippedDuplicate: 1 }); });
  it("reports repository errors without hiding partial writes", async () => { const repo = createInMemoryWorkItemRepository(); const failing = { ...repo, async saveWorkItem() { throw new Error("quota"); } }; const output = await initializeDemoWorkItemsFromResults([result("matching-proposal")], failing, options); expect(output).toMatchObject({ ok: false, code: "repository-error", created: 0 }); });
});
