import { describe, it, expect } from "vitest";
import { createInMemoryWorkItemRepository } from "@/lib/repositories/inMemoryWorkItemRepository";
import { startVisualHumanLoopDemo, resumeVisualHumanLoopDemo, VISUAL_HUMAN_LOOP_ID, startVisualNewClientDemo, VISUAL_NEW_CLIENT_ID, VISUAL_DEMO_SCENARIOS, VISUAL_BP_ID, startVisualBpDemo, BP_PREPARATION_MEMO } from "./visualOfficeHumanLoopDemo";
import { executeWorkItemCommandUseCase } from "./executeWorkItemCommand";
import { projectAgentActivity, nextPresentationIndex } from "@/lib/visual-office/agentActivity";
import { createSessionStorageWorkItemRepository } from "@/lib/repositories/sessionStorageWorkItemRepository";
import { approvalSnapshotForWorkItem } from "./prepareWorkItemApproval";
const at = "2026-10-01T00:00:00.000Z";
describe("BP面談準備Demo", () => {
  it("BP情報整理からhandoff、準備メモ、pendingまで進み既存2Demoに干渉しない", async () => {
    const repo = createInMemoryWorkItemRepository();
    await startVisualHumanLoopDemo(repo, at); await startVisualNewClientDemo(repo, at);
    const before = await repo.listWorkItems();
    const frames = await startVisualBpDemo(repo, at);
    expect(frames.map(frame => frame.activity)).toEqual(["working", "reviewing", "handoff", "reviewing", "working", "waiting_human"]);
    expect(frames[0]).toMatchObject({ agentId: "bp", text: "BP企業の特徴を整理中…" });
    expect(frames[2].handoff).toEqual({ from: "bp", to: "manager" });
    const item = (await repo.getWorkItem(VISUAL_BP_ID))!;
    expect(item).toMatchObject({ kind: "bp-alliance", status: "awaiting_approval", assignedAgentId: "manager", missingInfo: [], proposalDecisions: [], relations: { personIds: [], opportunityIds: [], partnerIds: ["demo-visual-bp"] } });
    expect(item.currentDeliverableId).toBeTruthy();
    expect(await repo.getApproval(item.currentApprovalId!)).toMatchObject({ state: "pending", scope: { permits: ["prepare-only"] } });
    expect(BP_PREPARATION_MEMO.themes).toHaveLength(3); expect(BP_PREPARATION_MEMO.questions).toHaveLength(3);
    expect(BP_PREPARATION_MEMO.share).toHaveLength(3); expect(BP_PREPARATION_MEMO.avoid).toHaveLength(2);
    expect(await startVisualBpDemo(repo, at)).toEqual([]);
    expect(await repo.listWorkItems()).toHaveLength(3);
    for (const other of before) expect(await repo.getWorkItem(other.id)).toEqual(other);
  });
  it.each(["approve-work-item", "reject-work-item", "return-for-rework"] as const)("%sとreload・再開始・表示再生でHuman状態を保持", async type => {
    const values = new Map<string, string>();
    const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); } };
    const repo = createSessionStorageWorkItemRepository(storage);
    const frames = await startVisualBpDemo(repo, at);
    const item = (await repo.getWorkItem(VISUAL_BP_ID))!; const approvalId = item.currentApprovalId!;
    const result = await executeWorkItemCommandUseCase({ repositories: repo, command: { type, commandId: "bp-decision", workItemId: item.id, approvalId, actorId: "demo-human", issuedAt: at, reason: "準備メモを修正してください" }, approvalSnapshots: { [approvalId]: approvalSnapshotForWorkItem(item) }, effectContext: { at, actor: { type: "human", id: "demo-human" } } });
    expect(result.ok).toBe(true);
    const reopened = createSessionStorageWorkItemRepository(storage);
    const saved = (await reopened.getWorkItem(item.id))!; const approval = (await reopened.getApproval(approvalId))!;
    expect(saved.status).toBe(type === "approve-work-item" ? "preparation_recorded" : "returned_for_rework");
    expect(projectAgentActivity(saved, approval)).toMatchObject(type === "approve-work-item" ? { activity: "completed", text: "Human面談準備確認完了（予約・外部送信なし）" } : { activity: "working", text: "準備メモの修正が必要です" });
    expect(saved.execution.lastAgentId).toBe("manager");
    for (let index = 0; index < frames.length; index++) nextPresentationIndex(index, frames.length);
    expect(await startVisualBpDemo(reopened, at)).toEqual([]);
    expect(await reopened.getWorkItem(item.id)).toEqual(saved);
    expect(await reopened.getApproval(approvalId)).toEqual(approval);
    expect(await reopened.listWorkItems()).toHaveLength(1);
  });
  it.each(["real", "non-demo"])("%sを固定ID経路で上書きしない", async invalid => {
    const repo = createInMemoryWorkItemRepository(); await startVisualBpDemo(repo, at);
    const item = (await repo.getWorkItem(VISUAL_BP_ID))!;
    const protectedItem = invalid === "real" ? { ...item, mode: "real" as const } : { ...item, source: { type: "manual" as const, ref: "non-demo" } };
    await repo.saveWorkItem(protectedItem);
    await expect(startVisualBpDemo(repo, at)).rejects.toThrow("demo-only");
    expect(await repo.getWorkItem(item.id)).toEqual(protectedItem);
  });
});
describe("新規顧客文案Demo", () => {
  it("4シナリオだけを選択対象にし、案件マッチングを先頭にする", () => {
    expect(VISUAL_DEMO_SCENARIOS.map(scenario => scenario.id)).toEqual(["matching", "outreach", "bp", "candidate"]);
    expect(new Set(VISUAL_DEMO_SCENARIOS.map(scenario => scenario.workItemId)).size).toBe(4);
  });
  it("既存案件Demoに干渉せず文案をprepare-onlyで準備し、重複しない", async () => {
    const repo = createInMemoryWorkItemRepository();
    await startVisualHumanLoopDemo(repo, at);
    const matching = await repo.getWorkItem(VISUAL_HUMAN_LOOP_ID);
    const frames = await startVisualNewClientDemo(repo, at);
    expect(frames.map(frame => frame.activity)).toEqual(["working", "handoff", "reviewing", "working", "waiting_human"]);
    expect(frames[0]).toMatchObject({ agentId: "newbiz", text: "アプローチ候補企業を整理中…" });
    expect(frames[1].handoff).toEqual({ from: "newbiz", to: "relation" });
    const item = (await repo.getWorkItem(VISUAL_NEW_CLIENT_ID))!;
    expect(item).toMatchObject({ kind: "new-client-outreach", assignedAgentId: "relation", missingInfo: [], proposalDecisions: [], status: "awaiting_approval" });
    expect(await repo.getApproval(item.currentApprovalId!)).toMatchObject({ state: "pending", scope: { permits: ["prepare-only"] } });
    expect(await startVisualNewClientDemo(repo, at)).toEqual([]);
    expect(await repo.listWorkItems()).toHaveLength(2);
    expect(await repo.getWorkItem(VISUAL_HUMAN_LOOP_ID)).toEqual(matching);
  });
  it.each(["approve-work-item", "reject-work-item", "return-for-rework"] as const)("%sを保存しreload・再開始でも巻き戻さない", async type => {
    const values = new Map<string, string>();
    const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); } };
    const repo = createSessionStorageWorkItemRepository(storage);
    await startVisualNewClientDemo(repo, at);
    const item = (await repo.getWorkItem(VISUAL_NEW_CLIENT_ID))!;
    const approvalId = item.currentApprovalId!;
    const result = await executeWorkItemCommandUseCase({ repositories: repo, command: { type, commandId: "decision", workItemId: item.id, approvalId, actorId: "demo-human", issuedAt: at, reason: "文案を修正してください" }, approvalSnapshots: { [approvalId]: approvalSnapshotForWorkItem(item) }, effectContext: { at, actor: { type: "human", id: "demo-human" } } });
    expect(result.ok).toBe(true);
    const reopened = createSessionStorageWorkItemRepository(storage);
    const saved = (await reopened.getWorkItem(item.id))!;
    const approval = (await reopened.getApproval(approvalId))!;
    expect(saved.status).toBe(type === "approve-work-item" ? "preparation_recorded" : "returned_for_rework");
    expect(projectAgentActivity(saved, approval)).toMatchObject(type === "approve-work-item" ? { activity: "completed", text: "Human文案確認完了（未送信）" } : { activity: "working", text: "文案の修正が必要です" });
    expect(await startVisualNewClientDemo(reopened, at)).toEqual([]);
    expect(await reopened.getWorkItem(item.id)).toEqual(saved);
    expect(await reopened.listWorkItems()).toHaveLength(1);
    expect(saved.execution.lastAgentId).toBe("relation");
  });
  it("real WorkItemを上書きしない", async () => {
    const repo = createInMemoryWorkItemRepository();
    await startVisualNewClientDemo(repo, at);
    const item = (await repo.getWorkItem(VISUAL_NEW_CLIENT_ID))!;
    await repo.saveWorkItem({ ...item, mode: "real" });
    await expect(startVisualNewClientDemo(repo, at)).rejects.toThrow("demo-only");
    expect((await repo.getWorkItem(item.id))?.mode).toBe("real");
  });
});
describe("Visual Office Human質問デモ", () => {
  it("案件整理から引き継ぎ、回答、再開、提案担当、pendingまで既存経路で進む", async () => {
    const repository = createInMemoryWorkItemRepository();
    const intro = await startVisualHumanLoopDemo(repository, at);
    expect(intro.map(frame => frame.activity)).toEqual(["working", "handoff", "working", "waiting_human"]);
    expect(intro[1].handoff).toEqual({ from: "manager", to: "matching" });
    let index = 0; for (let i = 0; i < 4; i++) index = nextPresentationIndex(index, intro.length);
    expect(index).toBe(3);
    const waiting = (await repository.getWorkItem(VISUAL_HUMAN_LOOP_ID))!;
    expect(waiting.status).toBe("blocked_missing_info"); expect(waiting.assignedAgentId).toBe("matching"); expect(waiting.missingInfo).toHaveLength(1);
    expect(projectAgentActivity(waiting).activity).toBe("waiting_human");
    expect(await startVisualHumanLoopDemo(repository, at)).toEqual([]);
    expect(await resumeVisualHumanLoopDemo(repository, at)).toEqual([]);
    const result = await executeWorkItemCommandUseCase({ repositories: repository, command: { type: "provide-missing-info", commandId: "demo-answer", workItemId: waiting.id, missingInfoId: waiting.missingInfo[0].id, actorId: "demo-human", issuedAt: at, value: { field: "availabilityStart", status: "matched", date: "2026-10-01" } }, effectContext: { at, actor: { type: "human", id: "demo-human" } } });
    expect(result.ok).toBe(true);
    const resume = await resumeVisualHumanLoopDemo(repository, at);
    expect(resume.map(frame => frame.activity)).toEqual(["reviewing", "working", "handoff", "waiting_human"]);
    expect(resume[2].handoff).toEqual({ from: "matching", to: "proposal" });
    const ready = (await repository.getWorkItem(waiting.id))!;
    const approval = await repository.getApproval(ready.currentApprovalId!);
    expect(ready).toMatchObject({ assignedAgentId: "proposal", status: "awaiting_approval" });
    expect(ready.nextAction).toMatchObject({ ownerType: "human", kind: "approve_or_reject" });
    expect(approval).toMatchObject({ state: "pending", scope: { permits: ["prepare-only"] } });
    expect(projectAgentActivity(ready, approval!).text).toContain("Human確認待ち");
    expect(await startVisualHumanLoopDemo(repository, at)).toEqual([]);
    expect(await repository.listWorkItems()).toHaveLength(1);
    expect(await resumeVisualHumanLoopDemo(repository, at)).toEqual([]);
  });
  it("real WorkItemを上書きしない", async () => {
    const repository = createInMemoryWorkItemRepository(); await startVisualHumanLoopDemo(repository, at);
    const item = (await repository.getWorkItem(VISUAL_HUMAN_LOOP_ID))!; await repository.saveWorkItem({ ...item, mode: "real" });
    await expect(startVisualHumanLoopDemo(repository, at)).rejects.toThrow("demo-only");
    expect((await repository.getWorkItem(item.id))?.mode).toBe("real");
  });
  it("不一致回答では再判定を進めずApprovalを作らない", async () => {
    const repo = createInMemoryWorkItemRepository(); await startVisualHumanLoopDemo(repo, at);
    const item = (await repo.getWorkItem(VISUAL_HUMAN_LOOP_ID))!;
    await executeWorkItemCommandUseCase({ repositories: repo, command: { type: "provide-missing-info", commandId: "mismatch", workItemId: item.id, missingInfoId: item.missingInfo[0].id, actorId: "demo-human", issuedAt: at, value: { field: "availabilityStart", status: "mismatched", date: "2026-10-01" } }, effectContext: { at, actor: { type: "human", id: "demo-human" } } });
    expect(await resumeVisualHumanLoopDemo(repo, at)).toEqual([]);
    expect((await repo.getWorkItem(item.id))?.currentApprovalId).toBeNull();
  });
  it.each(["approve-work-item", "reject-work-item", "return-for-rework"] as const)("%sを既存Commandで処理しreload相当でも保持", async type => {
    const values = new Map<string, string>();
    const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); } };
    const repo = createSessionStorageWorkItemRepository(storage);
    await startVisualHumanLoopDemo(repo, at);
    const item = (await repo.getWorkItem(VISUAL_HUMAN_LOOP_ID))!;
    const context = { at, actor: { type: "human" as const, id: "demo-human" } };
    await executeWorkItemCommandUseCase({ repositories: repo, command: { type: "provide-missing-info", commandId: "answer", workItemId: item.id, missingInfoId: item.missingInfo[0].id, actorId: "demo-human", issuedAt: at, value: { field: "availabilityStart", status: "matched", date: "2026-10-01" } }, effectContext: context });
    await resumeVisualHumanLoopDemo(repo, at);
    const current = (await repo.getWorkItem(item.id))!;
    const base = { commandId: "decision", workItemId: item.id, actorId: "demo-human", issuedAt: at };
    const command = type === "approve-work-item" ? { ...base, type, approvalId: current.currentApprovalId! } : type === "reject-work-item" ? { ...base, type, approvalId: current.currentApprovalId!, reason: "Demo再確認" } : { ...base, type, reason: "Demo再確認" };
    expect((await executeWorkItemCommandUseCase({ repositories: repo, command, approvalSnapshots: { [current.currentApprovalId!]: approvalSnapshotForWorkItem(current) }, effectContext: context })).ok).toBe(true);
    const reopened = createSessionStorageWorkItemRepository(storage);
    expect((await reopened.getWorkItem(item.id))?.status).toBe(type === "approve-work-item" ? "preparation_recorded" : "returned_for_rework");
    expect(await startVisualHumanLoopDemo(reopened, at)).toEqual([]);
    expect(await reopened.listWorkItems()).toHaveLength(1);
  });
});
